version: "2"

run:
    timeout: 3m

linters:
    enable:
        - errcheck
        - govet
        - ineffassign
        - revive
        - staticcheck

issues:
    max-issues-per-linter: 0
    max-same-issues: 0
